import React from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

function DownloadReport({ chartData, question, answer, chartRef }) {
  const handleDownload = async () => {
    const doc = new jsPDF();

    //  Title
    doc.setFontSize(16);
    doc.text("AI Data Analysis Report", 20, 20);

    //  Question
    doc.setFontSize(12);
    doc.text(`Question: ${question}`, 20, 40);

    // Answer
    doc.text(`Answer: ${answer}`, 20, 55);

    let y = 70;

    //  ADD CHART IMAGE (MAIN FIX)
    if (chartRef?.current) {
      const canvas = await html2canvas(chartRef.current);
      const imgData = canvas.toDataURL("image/png");

      doc.addImage(imgData, "PNG", 15, y, 180, 80);
      y += 90; // space after image
    }

    //  Data Header
    doc.text("Data:", 20, y);
    y += 10;

    //  Data rows
    chartData.forEach((item) => {
      doc.text(`${item[0]} : ${item[1]}`, 20, y);
      y += 8;
    });

    //  Footer
    doc.setFontSize(10);
    doc.text("Generated by AI Data Analyst", 20, y + 10);

    doc.save("report.pdf");
  };

  return (
    <button
      onClick={handleDownload}
      className="px-4 py-1 rounded-lg bg-green-600 hover:bg-green-700 transition"
    >
      📄 Download Report
    </button>
  );
}

export default DownloadReport;
